server:
  port: 8888
spring:
  application:
    name: reto-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Paeljofete/reto-config-server.git
        default-label: master
        search-paths:
        - '*server*'